r generator
kasptom/ProperTree pull request #1
Opened 2017-05-14 19:18 UTC by kasptom

2017-05-14 19:50 UTC, kasptom commented
![](https://github.trello.services/images/mini-trello-icon.png) [RFactory](https://trello.com/c/TD1boe88/5-rfactory)

2017-05-15 18:36 UTC, FreexD requested changes

2017-05-15 18:36 UTC, FreexD commented on src/main/java/pl/edu/agh/propertree/finder/ResourceFinder.java
>          Matcher matcher = POSTFIX_PATTERN.matcher(path);
prefix or postfix?

2017-05-15 18:36 UTC, FreexD commented on src/main/java/pl/edu/agh/propertree/generator/AddressGenerator.java
> +            Integer.parseInt(value);
int or boolean?

2017-05-15 18:36 UTC, FreexD commented on src/main/java/pl/edu/agh/propertree/generator/RGenerator.java
> + * Class which generates RHardcoded.java on basing on the configuration files
RHardcoded or R?

2017-05-15 18:45 UTC, FreexD approved these changes

2017-05-15 18:45 UTC, FreexD commented
LGTM

2017-05-15 19:54 UTC, merged